name: nessai-environment
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - pip
  - numpy
  - pandas
  - scipy>=0.16
  - matplotlib
  - seaborn
  - tqdm
  - pytorch>=1.7.0
  - torchvision
  - torchaudio
  - tensorboard
  - pip:
    - nflows
    - nessai
